### ISSUE TITLE
Why doesn't haveLength work with Seq?

### ISSUE THREAD

**Issue by NinoFloris** [fsprojects/FsUnit#105]
Why doesn't haveLength work with Seq?

Error is  System.ArgumentException : Property Length was not found

### Related information 
macOS, FsUnit.Xunit 1.4.1

**Comment by sergey-tihon** [comment]
Because implementation rely on reflection
https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.Xunit/CustomMatchers.fs#L115-L122
FsUnit assume that when you use `haveLength` you pass an object that has property `Length`

Anyway, the test works correctly. Unfortunately, you see an error during execution time, instead of compile time. But it fails because you assert that property `Length` should be and be equal to something and you obj have no such property.

**Comment by NinoFloris** [comment]
Seq is just an IEnumerable implementation, should really not be an issue to check for it. As it stands there is no builtin method to directly check against the count of any IEnumerable

**Comment by sergey-tihon** [comment]
I agree with you that in the perfect case would be nice to have one operator that checks the length of collection and works with any collection. But now we have [two different operators](http://fsprojects.github.io/FsUnit/operators.html) `haveLength` and `haveCount` (implemented across all supported frameworks). I guess that roots of this comes from `NUnit` (also have two).

One of the main ideas for this project is to be as close to existing frameworks as possible. It should provide an intuitive experience for users already familiar with other frameworks.

One more reason is backward compatibility. So I close this issue and thank you for the suggestion.

_P.S. If you are looking for unit testing framework that is purely functional (even test-cases are values),  designed for F# and where we do not need to maintain compatibility - try [Expecto](https://github.com/haf/expecto)_

**Comment by NinoFloris** [comment]
Yes expecto is great but for this project we try to keep everything in xunit for now, haveCount does not seem to work for ienumerables as it's not a property of them. That's why I opened this issue, there is no neat way to assert enumerable count
