### ISSUE TITLE
Some [] assert issue

### ISSUE THREAD

**Issue by huy-ngoduc** [fsprojects/FsUnit#113]
### Description

there is problem with Some [] comparation

### Repro steps

```fsharp
let rec safe_tl = function
    | [] -> None
    | h::t -> Some t

[Fact]
let ``Test safe_tl 1``() =
    Assert.Equal(Some [], safe_tl [3])

[Fact]
let ``Test safe_tl 2``() =
    safe_tl [3] |> should equal (Some [])
```

### Expected behavior

all tests should be passed

### Actual behavior
only  ``Test safe_tl 1`` passed

but ``Test safe_tl 2`` failed with following message

------ Run test started ------
[xUnit.net 00:00:00.8515084]   Starting:    CS3110.Tests
[xUnit.net 00:00:01.5357260]     CS3110.Tests.L4Test.Test safe_tl 2 [FAIL]
[xUnit.net 00:00:01.5388944]       FsUnit.Xunit+MatchException : Exception of type 'FsUnit.Xunit+MatchException' was thrown.
[xUnit.net 00:00:01.5396505]       Expected: Equals Some([])
[xUnit.net 00:00:01.5402443]       Actual:   was Some([])
[xUnit.net 00:00:01.5417230]       Stack Trace:
[xUnit.net 00:00:01.5424314]            at FsUnit.Xunit.Assert.That.Static[a](a actual, IMatcher`1 matcher)

### Related information 

* netcore45
* FsUnit.xUnit.3.0.0

**Comment by sergey-tihon** [comment]
@huy-ngoduc what is `netcore45`? ;) where I can download this?

this is kind-of known limitation of FsUnit DSL that comes to limits of F# type inference.
- `safe_tl [3]` has type `List<int>` this is obvious
-  `[]` has type `List<obj>` because the compiler does not have enough information to do better prediction.
- So, `Some<List<int>>` does not equal `Some<List<obj>>` even when lists are empty.


### Workaround 

Help compiler with type inference. Try following code sample

```fsharp
[Fact]
let ``Test safe_tl 2``() =
    safe_tl [3] |> should equal (Some <| List.empty<int> )
```

Sorry, but we probably won't fix it at the moment...

**Comment by huy-ngoduc** [comment]
@sergey-tihon:
Thanks a lot for your help.
> what is netcore45? ;) where I can download this? 
it's my mistake. I mean .net45 :)
