### ISSUE TITLE
should throw typeof<Exception> does not pass

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FsUnit#14]
This code does not pass:

    [<TestFixture>] 
    type ``Given a invalid connection string`` () =
        let connstr = @"lkjljlj"

        [<Test>] member x.
            ``An argument exception will be thrown.`` () = 
                connstr |> parseConnStrToRavenConn |> should throw typeof<System.ArgumentException>

Code throws a System.ArgumentException and, thus, should pass.

**Comment by sergey-tihon** [comment]
@halcwb @jbtule @juhan @vincpa 
Could you please test your samples with [FsUnit.xUnit 1.4.0-beta2](https://www.nuget.org/packages/FsUnit.xUnit/1.4.0-beta2)
I cannot reproduce this bug.

Unit tests for `throw` work as expected - https://github.com/fsprojects/FsUnit/blob/master/tests/FsUnit.Xunit.Test/raiseTests.fs#L12

I also have tried following tests
```fsharp
    [<Fact>] member test.``test1`` ()=
            (fun () -> [|1|].[2] |> ignore) |> should throw typeof<System.IndexOutOfRangeException>
    [<Fact>] member test.``test2`` ()=
            (fun () -> failwith "BOOM" |> ignore) |> should throw typeof<System.Exception>
```
They also work.

**Comment by juhan** [comment]
Having tested with FsUnit.NUnit version 1.4.0.0 from  NuGet in VS2013 update 4, VS2015 and MonoDevelop 4.0.12, plus I've seen it work in MonoDevelop 5.x, I can confirm that catching exceptions in the intended FsUnit way using lambda functions works as expected. Thanks!

But, at least for NUnit users, it may actually be simpler to use the original NUnit way to catch exceptions when otherwise using FsUnit:
```F#
  [<Test>]
  [<ExpectedException(typeof<System.IndexOutOfRangeException>)>]
  member test.test1 () =
    [|1|].[2] |> ignore

  [<Test>]
  [<ExpectedException(typeof<System.Exception>)>]
  member test.test2 () =
      failwith "BOOM" |> ignore
```
