### ISSUE TITLE
ofCase doesn't support generic union type

### ISSUE THREAD

**Issue by wenLiangcan** [fsprojects/FsUnit#190]
### Description

Checking case of generic union type throws `System.InvalidCastException`.

### Repro steps

```f#
type MyCase<'T> =
    | Case1 of 'T
    | Case2

let intCase1 = Case1 1
intCase1 |> should be (ofCase <@ Case1 @>)
```

### Expected behavior

The testing should be passed.

### Actual behavior

The following exception is throwed.
```
  Failed Test  [49 ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'Case1[System.Int32]' to type 'MyCase`1[System.Object]'.
  Stack Trace:
     at lambda_method34(Closure , Object )
   at FsUnit.Common.isOfCase@50.Invoke(a x)
   at FsUnit.CustomConstraints.OfSameCaseConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
   at FsUnit.TopLevelOperators.should[a,a](FSharpFunc`2 f, a x, Object y)
```

### Known workarounds

None.

### Related information 

* Windows 11
* FsUnit 4.0.6
* .NET 5

**Comment by sergey-tihon** [comment]
that is how type inference works in F#.
Compiler has no information to identify type of `Case1` inside quotation, that is why it uses most generic one MyCase<obj>

<img width="945" alt="image" src="https://user-images.githubusercontent.com/1197905/136668711-e293fe05-883d-4d85-98dc-903ad208aae3.png">

in this case you have to manually specify type to help compiler

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1197905/136668761-2e66274d-3d52-4ecf-b0cc-452b00d35311.png">

otherwise types are different and they should not be equal
