### ISSUE TITLE
Update docs site

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#210]
@CaptnCodr can you please help to republish docs site from `master` to make it up-to-date?

**Comment by CaptnCodr** [comment]
Yes, because of the v5.0 Release with FsUnitTyped changes etc.?

**Comment by sergey-tihon** [comment]
yes, we updated docs that FsUnitTyped is currently added to xUnit but forgot to update docs

**Comment by CaptnCodr** [comment]
Alright, I'll have time for that tomorrow. :)

**Comment by CaptnCodr** [comment]
I accidentally pushed directly to master, I hope the changes are ok.

**Comment by CaptnCodr** [comment]
@sergey-tihon Can you give me a 👍 if you approve? 
So I'll then release the docs and a new version with dependency updates as v5.0.1.

**Comment by CaptnCodr** [comment]
I had to remove the code example here to generate the new docs site because of the '@'-sign: https://github.com/fsprojects/FsUnit/commit/56d29e15a3cd2a6da544c2d9df1d5ba5a246dce3#diff-badc17ff44c87f5563ad36766e8d42f4dfdb140433e680a9d82c439136af9066R28
We have that code example in the docs, too.

After that all things are fine. Everything is now fixed and published.

**Comment by sergey-tihon** [comment]
Thank you @CaptnCodr !
