### ISSUE TITLE
It should be 1 file for referencing via Paket

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FsUnit#58]
//cc @tpetricek [original request](https://twitter.com/tomaspetricek/status/625404542985859073)

@tpetricek @forki  Why you do not like reference package from `NuGet`?

**Comment by tpetricek** [comment]
I just like the lightweight file references for simple things. In fact, I even copied `FsUnit.fs` by hand into a few of my projects.

As for technical reasons, it removes one part of the `FSharp.Core.dll` reference pain, because it just gets compiled as part of your project... (I had some hard time with conflicts between FsUnit and FsCheck in the past).

Nothing that could not be resolved, but I think FsUnit is simple enough that this scenario would be really nice to have.

**Comment by sergey-tihon** [comment]
This should be possible right now.
Here is [the guide](http://fsprojects.github.io/FsUnit/Paket.html)
